import { StyleSheet } from 'react-native';

const COLORS = {
  primary: '#00897B',
  primaryLight: '#27A69A',
  secondary: '#0B0F20',
  background: '#F7F8FA',
  white: '#FFFFFF',
  cardBg: '#FFFFFF',
  textMain: '#0B0F20',
  textSecondary: '#2C3440',
  textMuted: '#4E5D66',
  success: '#4CAF50',
  danger: '#C54545',
  lightGreen: '#E8F5E9',
  lightRed: '#FFEBEE',
  border: '#00000023',
  gradientStart: '#FFFFFF',
  gradientEnd: '#F7F8FA',
  chartBg: '#0B0F20',
  chartGrid: '#1F2937',
  tabPillBg: '#EEF0F4',
  sectionChevronBg: '#EEF0F4',
};

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  headerSection: {
    marginBottom: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoIcon: {
    width: 24,
    height: 24,
    marginRight: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 24,
    fontWeight: '600',
    color: COLORS.textMain,
    fontFamily: 'InterDisplaySemiBold',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  accountLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginBottom: 4,
    fontFamily: 'InterDisplayRegular',
  },
  accountNumber: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textMain,
    fontFamily: 'InterDisplaySemiBold',
  },
  detailsCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  detailsRow: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 16,
  },
  detailItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailTextContainer: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginBottom: 4,
    fontFamily: 'InterDisplayRegular',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.textMain,
    fontFamily: 'InterDisplayMedium',
  },
  tabContainer: {
    marginBottom: 20,
  },
  tabPill: {
    flexDirection: 'row',
    backgroundColor: COLORS.tabPillBg,
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: COLORS.white,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.textMuted,
    fontFamily: 'InterDisplayMedium',
  },
  tabTextActive: {
    color: COLORS.textMain,
  },
  portfolioCard: {
    backgroundColor: COLORS.chartBg,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  portfolioLabel: {
    fontSize: 12,
    color: COLORS.white,
    marginBottom: 12,
    opacity: 0.7,
    fontFamily: 'InterDisplayRegular',
  },
  portfolioHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  portfolioValue: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 4,
    fontFamily: 'InterDisplayBold',
  },
  portfolioChange: {
    fontSize: 14,
    color: COLORS.success,
    fontFamily: 'InterDisplayMedium',
  },
  openValue: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  openAmount: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.white,
    fontFamily: 'InterDisplaySemiBold',
  },
  openLabel: {
    fontSize: 12,
    color: COLORS.white,
    opacity: 0.7,
    fontFamily: 'InterDisplayRegular',
  },
  periodToggle: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  periodButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  periodButtonActive: {
    backgroundColor: COLORS.primaryLight,
  },
  periodText: {
    fontSize: 12,
    color: COLORS.white,
    opacity: 0.7,
    fontFamily: 'InterDisplayMedium',
  },
  periodTextActive: {
    opacity: 1,
  },
  chart: {
    marginVertical: 8,
    borderRadius: 16,
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.textMuted,
    opacity: 0.3,
  },
  paginationDotActive: {
    backgroundColor: COLORS.primary,
    opacity: 1,
    width: 24,
  },
  metricsSection: {
    marginBottom: 20,
  },
  metricsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textMain,
    marginBottom: 16,
    fontFamily: 'InterDisplaySemiBold',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    width: '48%',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  metricLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 8,
    marginBottom: 4,
    fontFamily: 'InterDisplayRegular',
  },
  metricValue: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.textMain,
    marginBottom: 4,
    fontFamily: 'InterDisplaySemiBold',
  },
  metricSubValue: {
    fontSize: 10,
    color: COLORS.textMuted,
    fontFamily: 'InterDisplayRegular',
  },
  metricChangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  metricChangeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InterDisplayMedium',
  },
  syncStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    marginBottom: 20,
  },
  syncText: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontFamily: 'InterDisplayRegular',
  },
});

export default styles;