import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  headerSection: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderColor: '#00000027',
    paddingBottom: 17,
  },
  logoIcon: {
    width: 39.37,
    height: 36,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  iconButton: {
    padding: 4,
  },
  accountSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 12,
  },
  accountLabel: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#4E5D66',
    marginBottom: 4,
  },
  accountNumber: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  upgradeCard: {
    backgroundColor: '#E0F2F1',
    borderRadius: 12,
    marginHorizontal: 20,
    marginTop: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  upgradeContent: {
    flex: 1,
  },
  upgradeTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
    marginBottom: 4,
  },
  upgradeSubtitle: {
    fontSize: 15,
    fontFamily: 'InstrumentSans-Regular',
  },
  upgradeSubtitleRegular: {
    fontWeight: '400',
    color: '#0B0F20',
  },
  upgradeSubtitleBold: {
    fontWeight: '700',
    fontFamily: 'InstrumentSans-Bold',
    color: '#0B0F20',
  },
  upgradeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00897B',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  upgradeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
  },
  TopTraders: {
    width: '90%',
    marginHorizontal: 20,
    paddingTop: 20,
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#0000004b',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    marginTop: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#2C3440',
  },
  sectionChevron: {
    width: 37,
    height: 37,
    borderRadius: 18.5,
    backgroundColor: '#EEF0F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceCard: {
    backgroundColor: '#0B0F20',
    borderRadius: 16,
    marginHorizontal: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  balanceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  balanceAmount: {
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  balanceChange: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#4DB6AC',
  },
  openPosition: {
    fontSize: 16,
    fontFamily: 'InstrumentSans-Regular',
    paddingTop: 30,
  },
  openAmount: {
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
  },
  openLabel: {
    fontWeight: '400',
    color: '#FFFFFF',
  },
  periodTabs: {
    flexDirection: 'row',
    marginBottom: 16,
    borderRadius: 8,
    backgroundColor: '#7E8A93',
  },
  periodTabs2: {
    flexDirection: 'row',
    marginBottom: 16,
    borderRadius: 8,
    backgroundColor: '#e6e6e6',
  },
  periodTab: {
    paddingVertical: 5,
    borderRadius: 8,
  },
  periodTabActive: {
    backgroundColor: '#27A69A',
  },
  periodTabText: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
    marginHorizontal: 32,
  },
  periodTabTextActive: {
    color: '#FFFFFF',
  },
  chart: {
    marginLeft: -20,
    borderRadius: 16,
  },
  metricsScroll: {
    paddingLeft: 20,
    marginTop: 20,
  },
  metricCard: {
    width: 150,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#00000023',
    marginRight: 12,
  },
  metricLabel: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#4E5D66',
    marginTop: 8,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
    marginBottom: 4,
  },
  metricChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metricChangeText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#00897B',
  },
  accountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    marginHorizontal: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#00000023',
  },
  accountCardFirst: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  accountCardLast: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  accountCardLeft: {
    flex: 1,
  },
  accountCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  accountCardNumber: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
  },
  accountCardBroker: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#2C3440',
  },
  accountCardRight: {
    alignItems: 'flex-end',
  },
  accountCardAmount: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
    marginBottom: 4,
  },
  accountCardChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  accountCardChangeText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#00897B',
  },
  copierScroll: {
    paddingLeft: 20,
    marginBottom: 8,
  },
  copierCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginRight: 12,
    width: 160,
    borderWidth: 1,
    borderColor: '#00000023',
  },
  copierName: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#0B0F20',
    marginBottom: 8,
  },
  copierStatusBadge: {
    borderWidth: 1,
    borderColor: '#00897B',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  copierStatusText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#00897B',
  },
  copierFollowers: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E67E22',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 6,
    alignSelf: 'flex-start',
  },
  copierFollowersText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
  },
  insightCard: {
    backgroundColor: '#00897B',
    borderRadius: 12,
    marginHorizontal: 20,
    padding: 20,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  insightTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
  },
  insightBadge: {
    flexDirection: 'row',
    backgroundColor: '#0B0F20',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  insightBadgeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
  },
  insightTime: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  insightDescription: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paginationDot: {
    width: 5,
    height: 5,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  paginationDotActive: {
    backgroundColor: '#FFFFFF',
    width: 15,
  },
  traderPeriodTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  traderPeriodTabActive: {
    backgroundColor: '#27A69A',
    marginHorizontal: 5,
  },
  traderPeriodTabActive2: {
    backgroundColor: '#27A69A',
  },
  traderPeriodTabText: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
  },
  traderPeriodTabText2: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#7E8A93',
    marginHorizontal: 35,
  },
  traderPeriodTabTextActive: {
    color: '#FFFFFF',
  },
  traderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 16,
    borderColor: '#0000004b',
  },
  traderCardFirst: {
    borderWidth: 0,
  },
  traderCardMiddle: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 0,
  },
  traderCardLast: {
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  traderBadge: {
    position: 'relative',
    width: 32,
    height: 34,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  traderRank: {
    position: 'absolute',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
  },
  traderInfo: {
    flex: 1,
  },
  traderName: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
    marginBottom: 4,
  },
  traderFollowers: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#2C3440',
  },
  traderPerformance: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  traderPerformanceText: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
});

export default styles;