import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  headerSection: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderColor: '#00000027',
    paddingBottom: 17,
  },
  logoIcon: {
    width: 39.37,
    height: 36,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  iconButton: {
    padding: 4,
  },
  accountSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 12,
  },
  accountLabel: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#4E5D66',
    marginBottom: 4,
  },
  accountNumber: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  tabContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  tabPill: {
    flexDirection: 'row',
    backgroundColor: '#D4DADF',
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabActive: {
    backgroundColor: '#00897B',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  roiTabsScroll: {
    marginTop: 20,
    paddingLeft: 20,
  },
  roiTabsContainer: {
    gap: 8,
    paddingRight: 20,
  },
  roiTab: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E1D6D6',
  },
  roiTabActive: {
    backgroundColor: '#00897B',
    borderColor: '#00897B',
  },
  roiTabText: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#7E8A93',
  },
  roiTabTextActive: {
    color: '#FFFFFF',
  },
  roiCard: {
    backgroundColor: '#0B0F20',
    borderRadius: 16,
    marginHorizontal: 20,
    marginTop: 20,
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  roiCardTitle: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
  },
  gaugeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeValueContainer: {
    alignItems: 'center',
    marginTop: -30,
  },
  gaugeValue: {
    fontSize: 32,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  gaugeChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  gaugeChangeText: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#00897B',
  },
  statisticsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 20,
    marginTop: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E3E3E3',
  },
  statisticsTitle: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#AAB3BA',
    marginBottom: 20,
  },
  statSection: {
    marginBottom: 24,
  },
  separator: {
    bottom: 10,
    height: 1,
    backgroundColor: '#E5E7EC',
    
  },
  statSectionWrap: {
    backgroundColor: '#F7F8FA',
    padding: 12,
    marginBottom: 15,
    borderRadius: 15,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#757575',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'InstrumentSans-Bold',
    color: '#00897B',
  },
  statValueLarge: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'InstrumentSans-Bold',
    color: '#212121',
  },
  statValueGreen: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#0B0F20',
  },
  statDetailRow: {
    marginBottom: 4,
  },
  statDetailText: {
    fontSize: 13,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#757575',
    lineHeight: 20,
  },
  openTradesValue: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  openTradesCount: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'InstrumentSans-Bold',
    color: '#212121',
  },
  openTradesProfit: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'InstrumentSans-Bold',
    color: '#00897B',
  },
  statRow: {
    marginBottom: 8,
  },
  statText: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#2C3440',
  },
  statDivider: {
    height: 1,
    backgroundColor: '#E3E3E3',
    marginVertical: 12,
  },
  insightsSection: {
    marginTop: 24,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#2C3440',
  },
  insightPriorityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0B0F20',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  insightPriorityText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
  },
  insightCard: {
    backgroundColor: '#00897B',
    borderRadius: 12,
    marginHorizontal: 20,
    padding: 20,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  insightTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'InstrumentSans-SemiBold',
    color: '#FFFFFF',
    marginRight: 8,
  },
  insightBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0B0F20',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  insightBadgeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'InstrumentSans-Medium',
    color: '#FFFFFF',
  },
  insightDescription: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'InstrumentSans-Regular',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paginationDot: {
    width: 5,
    height: 5,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  paginationDotActive: {
    backgroundColor: '#FFFFFF',
    width: 15,
  },
});

export default styles;